### ISSUE TITLE
type of masla should be the same in all clones

### ISSUE THREAD

**Issue by safarjal** [safarjal/hazthenewestapp#176]
because we will build the table based on it.... also for the moment let's disable date and time in compare mode, and just allow date onlu vs duration, as I have no idea what a compare table of date and time will look like.

**Comment by safarjal** [comment]
if type of masla is duration, then the top line in compare table showing months, and the second line showing dates, should go invis

**Comment by qwibbler** [comment]
> if type of masla is duration, then the top line in compare table showing months, and the second line showing dates, should go invis

done
