### ISSUE TITLE
Password Recursions

### ISSUE THREAD

**Issue by qwibbler** [safarjal/hazthenewestapp#32]
If the wrong password is entered the first time, even after putting the right password in next time, it leads you to an empty page.

Also, the wrong password recursion only recurses twice. If you fail twice, it leads you to an empty page to do as you please.

**Comment by safarjal** [comment]
ehh. password isn't a priority for me. If you wanna fix it, go ahead. Even putting in the password was sorta against my will, and it's the hackiest password job ever.
