### ISSUE TITLE
begins with 2 day istihaza

### ISSUE THREAD

**Issue by qwibbler** [safarjal/hazthenewestapp#55]
![image](https://user-images.githubusercontent.com/88380694/155491368-75ff9114-ab00-4ab5-bd7f-3d54bdf12405.png)

**Comment by safarjal** [comment]
if anything begins with 2 day istihaza... then if we have mawjooda paki, we will add to mawjooda paki and make it fasid and delete the first dam and tuhr.
if we don't have mawjooda, we will just delete first dam and tuhr
